name: ci

on: [push, pull_request]

jobs:
  test-php:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        php: ['7.0', '7.1', '7.2', '7.3', '7.4', '8.0', '8.1']
        tdengine: ['3.0.0.1']

    env:
      PHP_DOCKER_VERSION: ${{ matrix.php }}
      TDENGINE_DOCKER_VERSION: ${{ matrix.tdengine }}

    steps:
      - uses: actions/checkout@v2

      - name: prepare
        run: |
          cd .github
          docker-compose up -d
          docker exec php composer update

      - name: test
        run: docker exec php composer test

  test-tdengine:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        php: ['8.1']
        tdengine: ['2.4.0.30', '2.6.0.14']

    env:
      PHP_DOCKER_VERSION: ${{ matrix.php }}
      TDENGINE_DOCKER_VERSION: ${{ matrix.tdengine }}

    steps:
      - uses: actions/checkout@v2

      - name: prepare
        run: |
          cd .github
          docker-compose up -d
          docker exec php composer update

      - name: test
        run: docker exec php composer test
