name: Coding Standards

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        php: ['8.0']
        tdengine: ['3.0.0.1']

    env:
      PHP_DOCKER_VERSION: ${{ matrix.php }}
      TDENGINE_DOCKER_VERSION: ${{ matrix.tdengine }}

    steps:
      - uses: actions/checkout@v2

      - name: prepare
        run: |
          cd .github
          docker-compose up -d php
          docker exec php composer update

      - name: Test
        run: docker exec php ./vendor/bin/php-cs-fixer fix --dry-run --diff
